/**
 * Writes `src/version.ts` from `package.json` `version` so `VERSION` stays in sync without
 * duplicating semver by hand (and without JSON import attributes that conflict with the CJS build).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const v = pkg.version;
if (typeof v !== 'string' || v.length === 0) {
  throw new Error('package.json must contain a non-empty string "version"');
}

const out = `/**
 * Generated by scripts/sync-version.mjs from package.json — do not edit by hand.
 * Run \`npm run build\` or \`node scripts/sync-version.mjs\` after changing version.
 */
export const VERSION = ${JSON.stringify(v)} as const;
`;

writeFileSync(join(root, 'src', 'version.ts'), out);
