/**
 * Generated by scripts/sync-version.mjs from package.json — do not edit by hand.
 * Run `npm run build` or `node scripts/sync-version.mjs` after changing version.
 */
export const VERSION = "3.0.2" as const;
